on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Install Notation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Notation with azure-kv plugin
        uses: ./ # Uses an action in the root directory
        id: setup-azure-kv
        with:
          version: 1.0.0-rc.7
          key_name: example
          certificate_key_id: https://example-kv.vault.azure.net/keys/exampleCert/516954296d4d72db64644b2ab35721c2
          plugin_name: notation-azure-kv
          plugin_version: 0.6.0
      - name: check version
        run: notation version
      - name: check plugins
        run: notation plugin list
      - name: check notation keys
        run: notation key list
